AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: Sample-App

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        PYTHONPATH: /var/task
    Timeout: 29
    MemorySize: 256

Parameters: 
  CompanyName:
    Type: String
    AllowedValues:
      - shift
  ProjectName: 
    Type: String
    AllowedValues:
      - blog
  Environment:
    Type: String
    AllowedValues:
      - dev
      - stg
      - prd

Resources:
  APIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${CompanyName}-${ProjectName}-api
      CodeUri: .
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /{proxy+}
            Method: ANY
      Tags:
        Name: !Sub ${CompanyName}-${ProjectName}-api
        CompanyName: !Sub ${CompanyName}
        ProjectName: !Sub ${ProjectName}

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${CompanyName}-${ProjectName}-api
      StageName: stg
      Cors:
        AllowMethods: "'*'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
        MaxAge: "'600'"
      EndpointConfiguration:
        Type: REGIONAL
      Tags:
        Name: !Sub ${CompanyName}-${ProjectName}-api
        CompanyName: !Sub ${CompanyName}
        ProjectName: !Sub ${ProjectName}