AWSTemplateFormatVersion: "2010-09-09"

Transform: AWS::Serverless-2016-10-31

Description: Sample-App

Globals:
  Function:
    Runtime: python3.9
    Environment:
      Variables:
        PYTHONPATH: /var/task
    Timeout: 29
    MemorySize: 256

Parameters: 
  CompanyName:
    Type: String
    AllowedValues:
      - shift
  ProjectName: 
    Type: String
    AllowedValues:
      - blog
  DBUserName:
    Type: String
    Description: admin
    NoEcho: true
  DBPassword:
    Type: String
    Description: sp0e604cpyeU6OqxeTgI
    NoEcho: true
  DBEndPoint:
    Type: String
    Description: prd-echnavi-instance-2.c6blwgdoxjd7.ap-northeast-1.rds.amazonaws.com
  DBName:
    Type: String
    Description: echnavi_app
  DBPort:
    Type: String
    Description: 3306
    Default: "3306"

Resources:
  APIFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${CompanyName}-${ProjectName}-api
      CodeUri: .
      Handler: app.lambda_handler
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref APIGateway
            Path: /{proxy+}
            Method: ANY
      Tags:
        Name: !Sub ${CompanyName}-${ProjectName}-api
        CompanyName: !Sub ${CompanyName}
        ProjectName: !Sub ${ProjectName}
      Environment:
        Variables:
          USER_NAME: !Ref DBUserName
          PASSWORD: !Ref DBPassword
          END_POINT: !Ref DBEndPoint
          DB_NAME: !Ref DBName
          PORT: !Ref DBPort

  APIGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub ${CompanyName}-${ProjectName}-api
      StageName: stg
      EndpointConfiguration:
        Type: REGIONAL
      Tags:
        Name: !Sub ${CompanyName}-${ProjectName}-api
        CompanyName: !Sub ${CompanyName}
        ProjectName: !Sub ${ProjectName}